"""各语言的一句样例（给语言判断的测试用；都是自己写的通用句子）。"""
SAMPLES = {
    "zh": "这一页介绍新系统是怎么工作的，以及团队可以为客户做些什么。",
    "ja": "このスライドでは、新しいシステムの仕組みとチームが顧客のためにできることを説明します。",
    "ko": "이 슬라이드에서는 새로운 시스템이 어떻게 작동하는지 설명합니다.",
    "en": "This slide shows how we plan the new service and what the team can do to support our customers.",
    "de": "Auf dieser Folie sehen wir, wie das neue System funktioniert und was wir für die Kunden tun können.",
    "fr": "Cette diapositive présente le nouveau service et explique ce que nous pouvons faire pour les clients dans la région.",
    "es": "En esta diapositiva vemos cómo funciona el nuevo servicio y lo que el equipo puede hacer por los clientes.",
    "it": "In questa diapositiva vediamo come funziona il nuovo servizio e che cosa il team può fare per i clienti.",
    "nl": "Op deze dia zien we hoe het nieuwe systeem werkt en wat we voor de klanten kunnen doen in de regio.",
    "pl": "Na tym slajdzie widzimy, jak działa nowy system i co zespół może zrobić dla klientów w regionie.",
    "pt": "Neste slide vemos como funciona o novo serviço e o que a equipa pode fazer para os clientes da região.",
    "sv": "På den här bilden ser vi hur det nya systemet fungerar och vad vi kan göra för kunderna i regionen.",
    "da": "På dette dias ser vi, hvordan det nye system fungerer, og hvad vi kan gøre for kunderne i regionen.",
    "nb": "På dette lysbildet ser vi hvordan det nye systemet fungerer og hva vi kan gjøre for kundene i regionen.",
    "fi": "Tässä diassa näemme, miten uusi järjestelmä toimii ja mitä tiimi voi tehdä asiakkaiden hyväksi, kun palvelu alkaa.",
    "is": "Á þessari glæru sjáum við hvernig nýja kerfið virkar og hvað við getum gert fyrir viðskiptavini.",
    "et": "Sellel slaidil näeme, kuidas uus süsteem töötab ja mida meeskond saab klientide heaks teha, kui teenus algab.",
    "lv": "Šajā slaidā mēs redzam, kā darbojas jaunā sistēma un ko komanda var darīt klientu labā, lai tas būtu ērti.",
    "lt": "Šioje skaidrėje matome, kaip veikia nauja sistema ir ką komanda gali padaryti klientams, kad tai būtų patogu.",
    "cs": "Na tomto snímku vidíme, jak funguje nový systém a co může tým udělat pro zákazníky, aby to bylo pohodlné.",
    "sk": "Na tejto snímke vidíme, ako funguje nový systém a čo môže tím urobiť pre zákazníkov, aby to bolo pohodlné.",
    "hu": "Ezen a dián azt látjuk, hogy az új rendszer hogyan működik, és mit tehet a csapat az ügyfelekért.",
    "ro": "Pe acest slide vedem cum funcționează noul sistem și ce poate face echipa pentru clienți în această regiune.",
    "hr": "Na ovom slajdu vidimo kako novi sustav radi i što tim može učiniti za kupce u regiji.",
    "sl": "Na tem diapozitivu vidimo, kako deluje novi sistem in kaj lahko ekipa naredi za stranke v regiji.",
    "sq": "Në këtë diapozitiv shohim si funksionon sistemi i ri dhe çfarë mund të bëjë ekipi për klientët.",
    "ca": "En aquesta diapositiva veiem com funciona el nou sistema i què pot fer l'equip per als clients de la regió.",
    "gl": "Nesta diapositiva vemos como funciona o novo sistema e que pode facer o equipo polos clientes da rexión.",
    "ga": "Ar an sleamhnán seo feicimid conas a oibríonn an córas nua agus cad is féidir leis an bhfoireann a dhéanamh.",
    "cy": "Ar y sleid hon rydyn ni'n gweld sut mae'r system newydd yn gweithio a beth all y tîm ei wneud i'r cwsmeriaid.",
    "mt": "F'din is-slide naraw kif taħdem is-sistema l-ġdida u x'jista' jagħmel it-tim għall-klijenti tal-reġjun.",
    "tr": "Bu slaytta yeni sistemin nasıl çalıştığını ve ekibin müşteriler için neler yapabileceğini görüyoruz, bu çok önemli.",
    "el": "Σε αυτή τη διαφάνεια βλέπουμε πώς λειτουργεί το νέο σύστημα και τι μπορεί να κάνει η ομάδα.",
    "bg": "На този слайд виждаме как работи новата система и какво може да направи екипът за клиентите.",
    "mk": "На овој слајд гледаме како работи новиот систем и што може да направи тимот за клиентите.",
    "ru": "На этом слайде мы видим, как работает новая система и что команда может сделать для клиентов.",
    "sr": "На овом слајду видимо како нови систем ради и шта тим може да уради за купце.",
    "uk": "На цьому слайді ми бачимо, як працює нова система і що команда може зробити для клієнтів.",
    "th": "สไลด์นี้อธิบายว่าระบบใหม่ทำงานอย่างไรและทีมงานสามารถช่วยลูกค้าได้อย่างไร",
    "ar": "في هذه الشريحة نرى كيف يعمل النظام الجديد وما الذي يمكن للفريق فعله للعملاء.",
    "hi": "इस स्लाइड में हम देखते हैं कि नई प्रणाली कैसे काम करती है और टीम ग्राहकों के लिए क्या कर सकती है।",
    "vi": "Trong trang này chúng ta xem hệ thống mới hoạt động như thế nào và nhóm có thể làm gì cho khách hàng.",
}
